apiVersion: v1
kind: Pod
metadata:
  generateName: myapp
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: busybox
    command:
      - "sleep"
      - "10000000d"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
