apiVersion: v1
kind: Pod
metadata:
  generateName: myapp
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: mouhsen47/check-apps:0.1.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
