apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd
  name: list-apps
rules:
- apiGroups: [""]
  resources: ["applications"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watch-apps
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: list-apps
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  generateName: post-sync
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
  labels:
    name: post-sync
spec:
  restartPolicy: Never
  containers:
  - name: post-sync
    image: mouhsen47/check-apps:0.1.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
